export * from "./navbar/Navbar";
export * from "./main-section/MainSection";
export * from "./about/About";
export * from "./proyect/Proyects";
export * from "./skill/Skill";
export * from "./contact/Contact";
export * from "./footer/Footer";
export * from "./side-element/SideElement";
export * from "./side-element/SideElementRigth";
